[general]
static=yes
writeprotect=no

[default]
exten => s,1,NoOp(Starting outbound call)
 same => n,Answer()
 same => n,Wait(1)
 same => n,Playback(custom/output)
 same => n,Wait(1)
 same => n,Hangup()

exten => _X.,1,NoOp(Call to ${EXTEN})
 same => n,Answer()
 same => n,Wait(1)
 same => n,Playback(custom/${AUDIOFILE})
 same => n,Wait(1)
 same => n,Hangup()

[audiosocket]
exten => s,1,NoOp(AudioSocket for session ${SESSION_ID})
 same => n,AudioSocket(${SESSION_ID},host.docker.internal:9092)
 same => n,Hangup()

