[general]
enabled = yes
webenabled = no
port = 5038
bindaddr = 0.0.0.0

[goami]
secret = goamisecret123
permit = 127.0.0.1/255.255.255.255
permit = 172.16.0.0/12
permit = 10.0.0.0/8
read = all
write = all

